# YAML - abbrevated “YAML Ain’t markup language”  

# -case sentitive
# -file extension yml or yaml


name: "sri muthu rajesh"
occupation: 'programmer'
age: 23
gpa: 6.1
number: 1e+10
married: false
goodthings: null
curr_time: 2020-06-06 14:33:22

hobbies: 
  - tv
  - cricket  

dreams: ["house", "village", "good sleep"]  

devices:
  - name: "laptop"
    price: 20 
  - name: "mobile"
    age: 5
  - {name: "bike",age: 30}

decription: >
  the above greater than sign makes
  lines as single line so easy to read      #the above greater than sign makes lines as single line so easy to read 
#--------------------------------------------------------------------------------------------
reviews: |
  the above pipe symbol makes
  each line as multiple lines as it is
  opposite to > symbol

#Anchoring concept
version: &vers "2.2"   #now we can access version value by using *vers
season: *vers          #now season has same value as version

products: &prod
  name: fridge

boughtThings: 
  <<: *prod           #thus boughtThing got value as {name:frigde}
    
  
    
