remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap
- jekyll-feed
title: Tech Notes
description: This site includes all my tech learnings as a short notes!
markdown: kramdown