version: 2
jobs:
  build:
    machine: true
    steps:
      - run:
          name: Clone docs
          working_directory: ~/workdir
          command: |
            git clone --depth 1 https://github.com/srimuthurajesh/my-learnings.git
      - deploy:
          name: Trigger docs deployment
          working_directory: ~/workdir/docs
          command: |
            git config credential.helper 'cache --timeout=120'
            git config user.email "srimuthurajesh@gmail.com"
            git config user.name "srimuthurajesh"
            git commit --allow-empty -m "Trigger deployment"
            # Push quietly to prevent showing the token in log
            git push -q https://ac96f3afefec79dc74dc734b4c1fabf6f4d20453@github.com/srimuthurajesh/docs.git master